"""
This script serves to get the label and value of a certain correlation
coordinate in the heatmap created by sort_correlations.py.

Author: Maris Koopmans
"""

import numpy as np
import sys

def get_label(cf, coords, v):

	# Define the number of variables that are used
	num_vars = v - 1

	with open(cf) as f:
		lines = f.readlines()

	# Get the variable names in a list
	labels = [line.split(': ')[0] for line in lines]

	# Get the correlation values in a list
	values = [line.split(': ')[1] for line in lines]

	# Check if the coordinates are in the symmetric part of the heatmap
	if sum(coords) > num_vars:
		print('check')
		# If so, move them to the correct part in the upper half of the heatmap
		coords = [num_vars - coords[1], num_vars - coords[0]]

	# Get the place in the list where the desired label/value is at
	list_pos = sum([num_vars - i + 1 for i in range(coords[0])]) + coords[1]
	label = labels[list_pos]
	value = values[list_pos]

	return label, value

def main(f, nvars):

	# Ask for input as long as the user wants
	coords = input(f"Which coordinates of the heatmap do you want to know the labels of?").split(', ')

	while coords != ['q']:
		try:
			label, val = get_label(f, [int(coords[0]), int(coords[1])], nvars)
			print(f"The label of the coordinates is {label}. The correlation is {val}")
		except Exception as e:
			print(f"Error: {e}")

		coords = input(f"Which coordinates of the heatmap do you want to know the labels of?").split(', ')


if __name__ == '__main__':
	print(f"This script is used for getting the variables from the coordinates in the heatmap\
			generated by sort_correlations.py. The format for inputting the coordinates is \
			y_axis_coord, x_axis_coord. Press q to quit")
	label = sys.argv[1]
	n_vars = int(sys.argv[2])
	corr_file = f'correlations_{label}2.txt'
	main(corr_file, n_vars)